//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaAddMultiple.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kinoEntities : DbContext
    {
        public kinoEntities()
            : base("name=kinoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<FillmGenre> FillmGenres { get; set; }
        public virtual DbSet<Genre> Genres { get; set; }
        public virtual DbSet<FilmCountry> FilmCountries { get; set; }
        public virtual DbSet<Film> Films { get; set; }
    }
}
